<?php

use Illuminate\Database\Seeder;

class AuditsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('audits')->delete();
        
        \DB::table('audits')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Cidade',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nome":"Porto Alegre","estado_id":"1","img_cidade":"img\\/img_cidades\\/imagem_7690.jpeg","id":1}',
                'url' => 'http://localhost/cidades?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:26:48',
                'updated_at' => '2018-11-09 13:26:48',
            ),
            1 => 
            array (
                'id' => 2,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Cidade',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"nome":"Novo Hamburgo","estado_id":"1","img_cidade":"img\\/img_cidades\\/imagem_2176.jpeg","id":2}',
                'url' => 'http://localhost/cidades?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:26:59',
                'updated_at' => '2018-11-09 13:26:59',
            ),
            2 => 
            array (
                'id' => 3,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Cidade',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"nome":"S\\u00e3o Leopoldo","estado_id":"1","img_cidade":"img\\/img_cidades\\/imagem_6666.jpeg","id":3}',
                'url' => 'http://localhost/cidades?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:27:12',
                'updated_at' => '2018-11-09 13:27:12',
            ),
            3 => 
            array (
                'id' => 4,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Cidade',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"nome":"Pelotas","estado_id":"1","img_cidade":"img\\/img_cidades\\/imagem_9725.jpeg","id":4}',
                'url' => 'http://localhost/cidades?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:27:26',
                'updated_at' => '2018-11-09 13:27:26',
            ),
            4 => 
            array (
                'id' => 5,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Cidade',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"nome":"S\\u00e3o Paulo","estado_id":"2","img_cidade":"img\\/img_cidades\\/imagem_9308.jpeg","id":5}',
                'url' => 'http://localhost/cidades?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:27:42',
                'updated_at' => '2018-11-09 13:27:42',
            ),
            5 => 
            array (
                'id' => 6,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Cidade',
                'auditable_id' => 6,
                'old_values' => '[]',
                'new_values' => '{"nome":"Osasco","estado_id":"2","img_cidade":"img\\/img_cidades\\/imagem_7929.jpeg","id":6}',
                'url' => 'http://localhost/cidades?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:27:57',
                'updated_at' => '2018-11-09 13:27:57',
            ),
            6 => 
            array (
                'id' => 7,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Profissao',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nome":"Cozinheiro","descricao":"Cozinheiro teste","img_profissao":"img\\/img_profissoes\\/imagem_6301.jpeg","id":1}',
                'url' => 'http://localhost/profissoes?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:28:39',
                'updated_at' => '2018-11-09 13:28:39',
            ),
            7 => 
            array (
                'id' => 8,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Profissao',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"nome":"Engenheiro","descricao":"Engenheiro teste","img_profissao":"img\\/img_profissoes\\/imagem_3384.jpeg","id":2}',
                'url' => 'http://localhost/profissoes?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:28:55',
                'updated_at' => '2018-11-09 13:28:55',
            ),
            8 => 
            array (
                'id' => 9,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Profissao',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"nome":"Programador","descricao":"Programador teste","img_profissao":"img\\/img_profissoes\\/imagem_4144.jpeg","id":3}',
                'url' => 'http://localhost/profissoes?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:29:11',
                'updated_at' => '2018-11-09 13:29:11',
            ),
            9 => 
            array (
                'id' => 10,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Profissao',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"nome":"M\\u00e9dico","descricao":"M\\u00e9dico teste","img_profissao":"img\\/img_profissoes\\/imagem_1554.jpeg","id":4}',
                'url' => 'http://localhost/profissoes?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:29:34',
                'updated_at' => '2018-11-09 13:29:34',
            ),
            10 => 
            array (
                'id' => 11,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Profissao',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"nome":"Atendente","descricao":"Atendente teste","img_profissao":"img\\/img_profissoes\\/imagem_2758.jpeg","id":5}',
                'url' => 'http://localhost/profissoes?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:29:46',
                'updated_at' => '2018-11-09 13:29:46',
            ),
            11 => 
            array (
                'id' => 12,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Musica',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nome":"musica 1","id":1}',
                'url' => 'http://localhost/musicas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:30:10',
                'updated_at' => '2018-11-09 13:30:10',
            ),
            12 => 
            array (
                'id' => 13,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Musica',
                'auditable_id' => 2,
                'old_values' => '[]',
                'new_values' => '{"nome":"musica 2","id":2}',
                'url' => 'http://localhost/musicas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:30:18',
                'updated_at' => '2018-11-09 13:30:18',
            ),
            13 => 
            array (
                'id' => 14,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Musica',
                'auditable_id' => 3,
                'old_values' => '[]',
                'new_values' => '{"nome":"musica 3","id":3}',
                'url' => 'http://localhost/musicas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:30:23',
                'updated_at' => '2018-11-09 13:30:23',
            ),
            14 => 
            array (
                'id' => 15,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Musica',
                'auditable_id' => 4,
                'old_values' => '[]',
                'new_values' => '{"nome":"musica 4","id":4}',
                'url' => 'http://localhost/musicas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:30:27',
                'updated_at' => '2018-11-09 13:30:27',
            ),
            15 => 
            array (
                'id' => 16,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Musica',
                'auditable_id' => 5,
                'old_values' => '[]',
                'new_values' => '{"nome":"musica 5","id":5}',
                'url' => 'http://localhost/musicas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 13:30:32',
                'updated_at' => '2018-11-09 13:30:32',
            ),
            16 => 
            array (
                'id' => 17,
                'user_type' => 'App\\User',
                'user_id' => 1,
                'event' => 'created',
                'auditable_type' => 'App\\Pessoa',
                'auditable_id' => 1,
                'old_values' => '[]',
                'new_values' => '{"nome":"Oscar","cpf":"12121212121","cidade_id":"5","profissao_id":"3","id":1}',
                'url' => 'http://localhost/pessoas?',
                'ip_address' => '::1',
            'user_agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
                'tags' => NULL,
                'created_at' => '2018-11-09 14:01:49',
                'updated_at' => '2018-11-09 14:01:49',
            ),
        ));
        
        
    }
}